## Script For Scraping Covid data from Worlmeter Website
  - Stephen Kamau 
  - Email **stiveckamash@gmail.com**

In [3]:
#will be scapping data from worldmeter dashboeard
import pandas as pd
import urllib
import requests
from bs4 import BeautifulSoup as bs

In [4]:
url = 'https://www.worldometers.info/coronavirus/'
web_url = requests.get(url).text
soup = bs(web_url , 'html.parser')

In [6]:
# soup

In [105]:
#we need tr , td and tbody
# tbody === its for body of the table containing the data
# tr == row with data..
# td === cell with specific data
# thead == for heading of table

In [103]:
table = soup.find('tbody')

In [141]:
#ltes try getting the headings/columns..
head = soup.find('thead')

In [107]:
head

<thead>
<tr>
<th width="1%">#</th>
<th width="100">Country,<br>Other</br></th>
<th width="20">Total<br>Cases</br></th>
<th width="30">New<br>Cases</br></th>
<th width="30">Total<br>Deaths</br></th>
<th width="30">New<br>Deaths</br></th>
<th width="30">Total<br>Recovered</br></th>
<th width="30">New<br>Recovered</br></th>
<th width="30">Active<br/>Cases</th>
<th width="30">Serious,<br/>Critical</th>
<th width="30">Tot Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th width="30">Population</th>
<th style="display:none" width="30">Continent</th>
<th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
</tr>
</thead>

In [143]:
# cols = []
# # for head_row in head.findAll('tr'):
# for each_col in head.findAll('tr'):
#     print(each_col)
#     cols.append(each_col.text)
head

<thead>
<tr>
<th width="1%">#</th>
<th width="100">Country,<br>Other</br></th>
<th width="20">Total<br>Cases</br></th>
<th width="30">New<br>Cases</br></th>
<th width="30">Total<br>Deaths</br></th>
<th width="30">New<br>Deaths</br></th>
<th width="30">Total<br>Recovered</br></th>
<th width="30">New<br>Recovered</br></th>
<th width="30">Active<br/>Cases</th>
<th width="30">Serious,<br/>Critical</th>
<th width="30">Tot Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th width="30">Population</th>
<th style="display:none" width="30">Continent</th>
<th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
</tr>
</thead>

In [150]:
head.find("tr").text.split('\n')

['',
 '#',
 'Country,Other',
 'TotalCases',
 'NewCases',
 'TotalDeaths',
 'NewDeaths',
 'TotalRecovered',
 'NewRecovered',
 'ActiveCases',
 'Serious,Critical',
 'Tot\xa0Cases/1M pop',
 'Deaths/1M pop',
 'TotalTests',
 'Tests/',
 '1M pop',
 '',
 'Population',
 'Continent',
 '1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl',
 '']

In [151]:
cols = ["Country" ,"TotalCases" , "NewCases",
       "TotalDeaths" , "NewDeaths" ,"TotalRecovered",
       "NewRecovered" , "ActiveCases" , "Serious_Critical",
       "Total_Cases_per1M_pop" ,"Deaths_per1M_pop" , "TotalTests",
       "Test_per1M_pop" ,"Population" , "Continent"]

In [152]:
len(cols)

15

In [104]:
table

<tbody>
<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>3,974,355</td>
<td>+48,099</td>
<td>185,617</td>
<td>+855</td>
<td>1,826,096</td>
<td>+20,670</td>
<td>1,962,642</td>
<td>19,141</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="South America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>South America</nobr>
</td>
<td>2,861,919</td>
<td>+10,745</td>
<td>104,180</td>
<td>+266</td>
<td>1,868,527</td>
<td>+4,679</td>
<td>889,212</td>
<td>13,643</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="South America" style="display:none;">South America</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td>2,956,624</td>
<td>+53,838</td>
<td>70,013</td>
<td>+1,166</td>
<td>2,043,585</td>
<td>+41,653</td>
<td>843,026</td>
<td>19,735</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Europe</nobr>
</td>
<td>2,570,874</td>
<td>+11,162</td>
<td>196,565</td>
<td>+227</td>
<td>1,511,413</td>
<td>+6,589</td>
<td>862,896</td>
<td>5,345</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Europe" style="display:none;">Europe</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Africa</nobr>
</td>
<td>595,836</td>
<td>+14,196</td>
<td>13,065</td>
<td>+36</td>
<td>289,111</td>
<td>+1,187</td>
<td>293,660</td>
<td>968</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Africa" style="display:none;">Africa</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Oceania</nobr>
</td>
<td>11,460</td>
<td>+244</td>
<td>130</td>
<td>+1</td>
<td>9,331</td>
<td></td>
<td>1,999</td>
<td>17</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr></nobr>
</td>
<td>721</td>
<td></td>
<td>15</td>
<td></td>
<td>651</td>
<td></td>
<td>55</td>
<td>4</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="" style="display:none;"></td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world">
<td></td>
<td style="text-align:left;">World</td>
<td>12,971,789</td>
<td>+138,284</td>
<td>569,585</td>
<td>+2,551</td>
<td>7,548,714</td>
<td>+74,775</td>
<td>4,853,490</td>
<td>58,853</td>
<td>1,664</td>
<td>73.1</td>
<td></td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">3,395,092</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+39,446</td>
<td style="font-weight: bold; text-align:right;">137,660 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+258</td>
<td style="font-weight: bold; text-align:right">1,506,514</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+16,068</td>
<td style="text-align:right;font-weight:bold;">1,750,918</td>
<td style="font-weight: bold; text-align:right">15,802</td>
<td style="font-weight: bold; text-align:right">10,255</td>
<td style="font-weight: bold; text-align:right">416</td>
<td style="font-weight: bold; text-align:right">42,110,958</td>
<td style="font-weight: bold; text-align:right">127,200</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">331,060,504</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<td>98</td><td>2,405</td><td>8</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">1,846,249</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+5,437</td>
<td style="font-weight: bold; text-align:right;">71,584 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+92</td>
<td style="font-weight: bold; text-align:right">1,213,512</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">561,153</td>
<td style="font-weight: bold; text-align:right">8,318</td>
<td style="font-weight: bold; text-align:right">8,684</td>
<td style="font-weight: bold; text-align:right">337</td>
<td style="font-weight: bold; text-align:right">4,572,796</td>
<td style="font-weight: bold; text-align:right">21,509</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">212,603,520</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>115</td><td>2,970</td><td>46</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">879,466</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+29,108</td>
<td style="font-weight: bold; text-align:right;">23,187 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+500</td>
<td style="font-weight: bold; text-align:right">554,429</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+18,198</td>
<td style="text-align:right;font-weight:bold;">301,850</td>
<td style="font-weight: bold; text-align:right">8,944</td>
<td style="font-weight: bold; text-align:right">637</td>
<td style="font-weight: bold; text-align:right">17</td>
<td style="font-weight: bold; text-align:right">11,587,153</td>
<td style="font-weight: bold; text-align:right">8,394</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,380,381,949</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>1,570</td><td>59,533</td><td>119</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">727,162</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+6,615</td>
<td style="font-weight: bold; text-align:right;">11,335 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+130</td>
<td style="font-weight: bold; text-align:right">501,061</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+3,615</td>
<td style="text-align:right;font-weight:bold;">214,766</td>
<td style="font-weight: bold; text-align:right">2,300</td>
<td style="font-weight: bold; text-align:right">4,983</td>
<td style="font-weight: bold; text-align:right">78</td>
<td style="font-weight: bold; text-align:right">23,031,056</td>
<td style="font-weight: bold; text-align:right">157,816</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,936,493</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>201</td><td>12,875</td><td>6</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/peru/">Peru</a></td>
<td style="font-weight: bold; text-align:right">322,710</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">11,682 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">214,152</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">96,876</td>
<td style="font-weight: bold; text-align:right">1,315</td>
<td style="font-weight: bold; text-align:right">9,784</td>
<td style="font-weight: bold; text-align:right">354</td>
<td style="font-weight: bold; text-align:right">1,904,242</td>
<td style="font-weight: bold; text-align:right">57,733</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/peru-population/">32,983,682</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>102</td><td>2,823</td><td>17</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/chile/">Chile</a></td>
<td style="font-weight: bold; text-align:right">315,041</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+3,012</td>
<td style="font-weight: bold; text-align:right;">6,979 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+98</td>
<td style="font-weight: bold; text-align:right">283,902</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+2,788</td>
<td style="text-align:right;font-weight:bold;">24,160</td>
<td style="font-weight: bold; text-align:right">1,995</td>
<td style="font-weight: bold; text-align:right">16,476</td>
<td style="font-weight: bold; text-align:right">365</td>
<td style="font-weight: bold; text-align:right">1,292,798</td>
<td style="font-weight: bold; text-align:right">67,612</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/chile-population/">19,120,870</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>61</td><td>2,740</td><td>15</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>
<td style="font-weight: bold; text-align:right">300,988</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">28,403 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right;">N/A</td>
<td style="text-align:right;font-weight:bold;">N/A</td>
<td style="font-weight: bold; text-align:right">617</td>
<td style="font-weight: bold; text-align:right">6,438</td>
<td style="font-weight: bold; text-align:right">607</td>
<td style="font-weight: bold; text-align:right">5,734,599</td>
<td style="font-weight: bold; text-align:right">122,651</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/spain-population/">46,755,366</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>155</td><td>1,646</td><td>8</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/mexico/">Mexico</a></td>
<td style="font-weight: bold; text-align:right">295,268</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+6,094</td>
<td style="font-weight: bold; text-align:right;">34,730 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+539</td>
<td style="font-weight: bold; text-align:right">180,852</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+3,755</td>
<td style="text-align:right;font-weight:bold;">79,686</td>
<td style="font-weight: bold; text-align:right">378</td>
<td style="font-weight: bold; text-align:right">2,289</td>
<td style="font-weight: bold; text-align:right">269</td>
<td style="font-weight: bold; text-align:right">723,668</td>
<td style="font-weight: bold; text-align:right">5,611</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/mexico-population/">128,969,990</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<td>437</td><td>3,714</td><td>178</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">289,603</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+650</td>
<td style="font-weight: bold; text-align:right;">44,819 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+21</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right;">N/A</td>
<td style="text-align:right;font-weight:bold;">N/A</td>
<td style="font-weight: bold; text-align:right">185</td>
<td style="font-weight: bold; text-align:right">4,265</td>
<td style="font-weight: bold; text-align:right">660</td>
<td style="font-weight: bold; text-align:right">11,990,257</td>
<td style="font-weight: bold; text-align:right">176,595</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">67,896,748</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>234</td><td>1,515</td><td>6</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-africa/">South Africa</a></td>
<td style="font-weight: bold; text-align:right">276,242</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+12,058</td>
<td style="font-weight: bold; text-align:right;">3,971 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">127,715</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">144,556</td>
<td style="font-weight: bold; text-align:right">539</td>
<td style="font-weight: bold; text-align:right">4,656</td>
<td style="font-weight: bold; text-align:right">67</td>
<td style="font-weight: bold; text-align:right">2,108,570</td>
<td style="font-weight: bold; text-align:right">35,541</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/south-africa-population/">59,328,450</a> </td>
<td data-continent="Africa" style="display:none">Africa</td>
<td>215</td><td>14,940</td><td>28</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/iran/">Iran</a></td>
<td style="font-weight: bold; text-align:right">257,303</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+2,186</td>
<td style="font-weight: bold; text-align:right;">12,829 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+194</td>
<td style="font-weight: bold; text-align:right">219,993</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+2,327</td>
<td style="text-align:right;font-weight:bold;">24,481</td>
<td style="font-weight: bold; text-align:right">3,359</td>
<td style="font-weight: bold; text-align:right">3,062</td>
<td style="font-weight: bold; text-align:right">153</td>
<td style="font-weight: bold; text-align:right">1,972,207</td>
<td style="font-weight: bold; text-align:right">23,473</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/iran-population/">84,021,254</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>327</td><td>6,549</td><td>43</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">12</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/pakistan/">Pakistan</a></td>
<td style="font-weight: bold; text-align:right">248,872</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+2,521</td>
<td style="font-weight: bold; text-align:right;">5,197 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+74</td>
<td style="font-weight: bold; text-align:right">156,700</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+3,566</td>
<td style="text-align:right;font-weight:bold;">86,975</td>
<td style="font-weight: bold; text-align:right">2,118</td>
<td style="font-weight: bold; text-align:right">1,126</td>
<td style="font-weight: bold; text-align:right">24</td>
<td style="font-weight: bold; text-align:right">1,562,638</td>
<td style="font-weight: bold; text-align:right">7,071</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/pakistan-population/">220,990,656</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>888</td><td>42,523</td><td>141</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">13</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
<td style="font-weight: bold; text-align:right">243,061</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+234</td>
<td style="font-weight: bold; text-align:right;">34,954 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+9</td>
<td style="font-weight: bold; text-align:right">194,928</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+349</td>
<td style="text-align:right;font-weight:bold;">13,179</td>
<td style="font-weight: bold; text-align:right">68</td>
<td style="font-weight: bold; text-align:right">4,020</td>
<td style="font-weight: bold; text-align:right">578</td>
<td style="font-weight: bold; text-align:right">5,938,811</td>
<td style="font-weight: bold; text-align:right">98,229</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,458,858</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>249</td><td>1,730</td><td>10</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">14</td>

In [94]:
# for x in table.findAll('tbody'):
#     print("Hello")

In [99]:
#define a list to hold table data
table_data = []

In [100]:
#let loop throu tr and td making the data
for each_row in table.findAll('tr'):
    row_data = []
    for each_cell in each_row.findAll('td'):
        row_data.append(each_cell.text)
        
#     table_data.append(row_data)
    if (len(row_data)>0):
#         print(row_data[2])
#         country_data = {
#             "country":row_data[0],
#             "total_cases":row_data[1],
#             "new_cases":row_data[2],
#             'total_deaths':row_data[3],
#             "new_deaths":row_data[4],
#             "total_recovered":row_data[5],
#             "active_cases":row_data[6],
#             "critical_cases":row_data[7],
#             "total_cases_per_1M":row_data[8],
#             "total_deaths_per_1M":row_data[9],
#             "total_tests":row_data[10],
#             "total_tests_per_1M":row_data[11],
#             "population":row_data[14]
#         }
            
            
        table_data.append(row_data)

In [153]:
# table_data
# row_data
df =pd.DataFrame(table_data )

In [154]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,,\nNorth America\n,"3,974,355","+48,099","185,617",+855,"1,826,096","+20,670","1,962,642","19,141",,,,,,North America,\n,,
1,,\nSouth America\n,"2,861,919","+10,745","104,180",+266,"1,868,527","+4,679","889,212","13,643",,,,,,South America,\n,,
2,,\nAsia\n,"2,956,624","+53,838","70,013","+1,166","2,043,585","+41,653","843,026","19,735",,,,,,Asia,\n,,
3,,\nEurope\n,"2,570,874","+11,162","196,565",+227,"1,511,413","+6,589","862,896","5,345",,,,,,Europe,\n,,
4,,\nAfrica\n,"595,836","+14,196","13,065",+36,"289,111","+1,187","293,660",968,,,,,,Africa,\n,,

In [157]:
#drop the col 0 ,16 ,17,18
df.drop([0 ,16,17,18], inplace = True , axis =1)

In [158]:
df.head()

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,\nNorth America\n,"3,974,355","+48,099","185,617",+855,"1,826,096","+20,670","1,962,642","19,141",,,,,,North America
1,\nSouth America\n,"2,861,919","+10,745","104,180",+266,"1,868,527","+4,679","889,212","13,643",,,,,,South America
2,\nAsia\n,"2,956,624","+53,838","70,013","+1,166","2,043,585","+41,653","843,026","19,735",,,,,,Asia
3,\nEurope\n,"2,570,874","+11,162","196,565",+227,"1,511,413","+6,589","862,896","5,345",,,,,,Europe
4,\nAfrica\n,"595,836","+14,196","13,065",+36,"289,111","+1,187","293,660",968,,,,,,Africa

In [160]:
df.columns = cols

In [161]:
df.head()

,Country,TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,Serious_Critical,Total_Cases_per1M_pop,Deaths_per1M_pop,TotalTests,Test_per1M_pop,Population,Continent
0,\nNorth America\n,"3,974,355","+48,099","185,617",+855,"1,826,096","+20,670","1,962,642","19,141",,,,,,North America
1,\nSouth America\n,"2,861,919","+10,745","104,180",+266,"1,868,527","+4,679","889,212","13,643",,,,,,South America
2,\nAsia\n,"2,956,624","+53,838","70,013","+1,166","2,043,585","+41,653","843,026","19,735",,,,,,Asia
3,\nEurope\n,"2,570,874","+11,162","196,565",+227,"1,511,413","+6,589","862,896","5,345",,,,,,Europe
4,\nAfrica\n,"595,836","+14,196","13,065",+36,"289,111","+1,187","293,660",968,,,,,,Africa